/*
 * file: WebPageStatus_ruInit.cpp
 *
 * Implementation for WebPageStatus_Init
 *
 * $Author: $
 * $Date: $
 * $Revision: $
 *
 *
 */

/* INCLUDES */

#include "WebPageStatus.hpp"

/* END OF INCLUDES */

/* MACROS */
/* END OF MACROS */

/* TYPE DEFINITIONS */
/* END OF TYPE DEFINITIONS */

/* VARIABLES */
/* END OF VARIABLES */

/* LOCAL FUNCTION DECLARATIONS */
/* END OF LOCAL FUNCTION DECLARATIONS */

/* LOCAL FUNCTION DEFINITIONS */
/* END OF LOCAL FUNCTION DEFINITIONS */

/* PRIVATE FUNCTION DEFINITIONS */
/* END OF PRIVATE FUNCTION DEFINITIONS */

/* PROTECTED FUNCTION DEFINITIONS */
/* END OF PROTECTED FUNCTION DEFINITIONS */

/* PUBLIC FUNCTION DEFINITIONS */

void WebPageStatus::ruInit(void)
{
    
}

/* END OF PUBLIC FUNCTION DEFINITIONS */

/* End of file */
